[package]
name = "lmh01_pathfinding"
version = "4.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
steps = []
mermaid = []

[dependencies]
